interfaces:
  access:
  - address:
      __datatype: str
      __label: interfaces/access/address
      __options: []
      __value: 103.145.5.10
      __widget: text_input
    address-iter:
      __datatype: str
      __label: interfaces/access/address-iter
      __options: []
      __value: 0.0.0.1
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/access/gateway
      __options: []
      __value: 103.145.5.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/access/interface
      __options: []
      __value: ens17.400
      __widget: text_input
    ipv6:
      __datatype: bool
      __label: interfaces/access/ipv6
      __options:
      - true
      - false
      __value: false
      __widget: selectbox
    stream-group-id:
      __datatype: int
      __label: interfaces/access/stream-group-id
      __options:
        __max: 65535
        __min: 0
        __step: 1000
      __value: 100
      __widget: number_input
    type:
      __datatype: str
      __label: interfaces/access/type
      __options:
      - pppoe
      - ipoe
      __value: ipoe
      __widget: selectbox
    vlan-mode:
      __datatype: str
      __label: interfaces/access/vlan-mode
      __options:
      - '1:1'
      - N:1
      __value: N:1
      __widget: selectbox
  - address:
      __datatype: str
      __label: interfaces/access/address
      __options: []
      __value: 103.145.6.10
      __widget: text_input
    address-iter:
      __datatype: str
      __label: interfaces/access/address-iter
      __options: []
      __value: 0.0.0.1
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/access/gateway
      __options: []
      __value: 103.145.6.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/access/interface
      __options: []
      __value: ens17.401
      __widget: text_input
    ipv6:
      __datatype: bool
      __label: interfaces/access/ipv6
      __options:
      - true
      - false
      __value: false
      __widget: selectbox
    stream-group-id:
      __datatype: int
      __label: interfaces/access/stream-group-id
      __options:
        __max: 65535
        __min: 0
        __step: 1000
      __value: 101
      __widget: number_input
    type:
      __datatype: str
      __label: interfaces/access/type
      __options:
      - pppoe
      - ipoe
      __value: ipoe
      __widget: selectbox
    vlan-mode:
      __datatype: str
      __label: interfaces/access/vlan-mode
      __options:
      - '1:1'
      - N:1
      __value: N:1
      __widget: selectbox
  - address:
      __datatype: str
      __label: interfaces/access/address
      __options: []
      __value: 103.145.7.10
      __widget: text_input
    address-iter:
      __datatype: str
      __label: interfaces/access/address-iter
      __options: []
      __value: 0.0.0.1
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/access/gateway
      __options: []
      __value: 103.145.7.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/access/interface
      __options: []
      __value: ens17.402
      __widget: text_input
    ipv6:
      __datatype: bool
      __label: interfaces/access/ipv6
      __options:
      - true
      - false
      __value: false
      __widget: selectbox
    stream-group-id:
      __datatype: int
      __label: interfaces/access/stream-group-id
      __options:
        __max: 65535
        __min: 0
        __step: 1000
      __value: 102
      __widget: number_input
    type:
      __datatype: str
      __label: interfaces/access/type
      __options:
      - pppoe
      - ipoe
      __value: ipoe
      __widget: selectbox
    vlan-mode:
      __datatype: str
      __label: interfaces/access/vlan-mode
      __options:
      - '1:1'
      - N:1
      __value: N:1
      __widget: selectbox
  - address:
      __datatype: str
      __label: interfaces/access/address
      __options: []
      __value: 103.145.8.10
      __widget: text_input
    address-iter:
      __datatype: str
      __label: interfaces/access/address-iter
      __options: []
      __value: 0.0.0.1
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/access/gateway
      __options: []
      __value: 103.145.8.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/access/interface
      __options: []
      __value: ens17.403
      __widget: text_input
    ipv6:
      __datatype: bool
      __label: interfaces/access/ipv6
      __options:
      - true
      - false
      __value: false
      __widget: selectbox
    stream-group-id:
      __datatype: int
      __label: interfaces/access/stream-group-id
      __options:
        __max: 65535
        __min: 0
        __step: 1000
      __value: 103
      __widget: number_input
    type:
      __datatype: str
      __label: interfaces/access/type
      __options:
      - pppoe
      - ipoe
      __value: ipoe
      __widget: selectbox
    vlan-mode:
      __datatype: str
      __label: interfaces/access/vlan-mode
      __options:
      - '1:1'
      - N:1
      __value: N:1
      __widget: selectbox
  - address:
      __datatype: str
      __label: interfaces/access/address
      __options: []
      __value: 103.145.9.10
      __widget: text_input
    address-iter:
      __datatype: str
      __label: interfaces/access/address-iter
      __options: []
      __value: 0.0.0.1
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/access/gateway
      __options: []
      __value: 103.145.9.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/access/interface
      __options: []
      __value: ens17.404
      __widget: text_input
    ipv6:
      __datatype: bool
      __label: interfaces/access/ipv6
      __options:
      - true
      - false
      __value: false
      __widget: selectbox
    stream-group-id:
      __datatype: int
      __label: interfaces/access/stream-group-id
      __options:
        __max: 65535
        __min: 0
        __step: 1000
      __value: 104
      __widget: number_input
    type:
      __datatype: str
      __label: interfaces/access/type
      __options:
      - pppoe
      - ipoe
      __value: ipoe
      __widget: selectbox
    vlan-mode:
      __datatype: str
      __label: interfaces/access/vlan-mode
      __options:
      - '1:1'
      - N:1
      __value: N:1
      __widget: selectbox
  - address:
      __datatype: str
      __label: interfaces/access/address
      __options: []
      __value: 103.145.10.10
      __widget: text_input
    address-iter:
      __datatype: str
      __label: interfaces/access/address-iter
      __options: []
      __value: 0.0.0.1
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/access/gateway
      __options: []
      __value: 103.145.10.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/access/interface
      __options: []
      __value: ens17.405
      __widget: text_input
    ipv6:
      __datatype: bool
      __label: interfaces/access/ipv6
      __options:
      - true
      - false
      __value: false
      __widget: selectbox
    stream-group-id:
      __datatype: int
      __label: interfaces/access/stream-group-id
      __options:
        __max: 65535
        __min: 0
        __step: 1000
      __value: 105
      __widget: number_input
    type:
      __datatype: str
      __label: interfaces/access/type
      __options:
      - pppoe
      - ipoe
      __value: ipoe
      __widget: selectbox
    vlan-mode:
      __datatype: str
      __label: interfaces/access/vlan-mode
      __options:
      - '1:1'
      - N:1
      __value: N:1
      __widget: selectbox
  - address:
      __datatype: str
      __label: interfaces/access/address
      __options: []
      __value: 103.145.11.10
      __widget: text_input
    address-iter:
      __datatype: str
      __label: interfaces/access/address-iter
      __options: []
      __value: 0.0.0.1
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/access/gateway
      __options: []
      __value: 103.145.11.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/access/interface
      __options: []
      __value: ens17.406
      __widget: text_input
    ipv6:
      __datatype: bool
      __label: interfaces/access/ipv6
      __options:
      - true
      - false
      __value: false
      __widget: selectbox
    stream-group-id:
      __datatype: int
      __label: interfaces/access/stream-group-id
      __options:
        __max: 65535
        __min: 0
        __step: 1000
      __value: 106
      __widget: number_input
    type:
      __datatype: str
      __label: interfaces/access/type
      __options:
      - pppoe
      - ipoe
      __value: ipoe
      __widget: selectbox
    vlan-mode:
      __datatype: str
      __label: interfaces/access/vlan-mode
      __options:
      - '1:1'
      - N:1
      __value: N:1
      __widget: selectbox
  io-slots:
    __datatype: str
    __label: interfaces/io-slots
    __options: []
    __value: 65535
    __widget: text_input
  network:
  - address:
      __datatype: str
      __label: interfaces/network/address
      __options: []
      __value: 103.141.141.128/24
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/network/gateway
      __options: []
      __value: 103.141.141.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/network/interface
      __options: []
      __value: ens16.400
      __widget: text_input
  rx-threads:
    __datatype: str
    __label: interfaces/rx-threads
    __options: []
    __value: 5
    __widget: text_input
  tx-threads:
    __datatype: str
    __label: interfaces/tx-threads
    __options: []
    __value: 5
    __widget: text_input
sessions:
  count:
    __datatype: str
    __label: sessions/count
    __options: []
    __value: 7
    __widget: text_input
streams:
- Mbps:
    __datatype: float
    __label: streams/Mbps
    __options:
      __max: 1024.0
      __min: 0.0
      __step: 10.0
    __value: 500.0
    __widget: number_input
  direction:
    __datatype: str
    __label: streams/direction
    __options:
    - both
    - upstream
    - downstream
    __value: both
    __widget: selectbox
  length:
    __datatype: int
    __label: streams/length
    __options:
      __max: 9000
      __min: 76
      __step: 100
    __value: 3936
    __widget: number_input
  name:
    __datatype: str
    __label: streams/name
    __options: []
    __value: H2
    __widget: text_input
  stream-group-id:
    __datatype: str
    __label: streams/stream-group-id
    __options: []
    __value: 100
    __widget: text_input
  type:
    __datatype: str
    __label: streams/type
    __options:
    - ipv4
    - ipv6
    - ipv6pd
    __value: ipv4
    __widget: selectbox
- Mbps:
    __datatype: float
    __label: streams/Mbps
    __options:
      __max: 1024.0
      __min: 0.0
      __step: 10.0
    __value: 500.0
    __widget: number_input
  direction:
    __datatype: str
    __label: streams/direction
    __options:
    - both
    - upstream
    - downstream
    __value: both
    __widget: selectbox
  length:
    __datatype: int
    __label: streams/length
    __options:
      __max: 9000
      __min: 76
      __step: 100
    __value: 3900
    __widget: number_input
  name:
    __datatype: str
    __label: streams/name
    __options: []
    __value: AF
    __widget: text_input
  stream-group-id:
    __datatype: str
    __label: streams/stream-group-id
    __options: []
    __value: 101
    __widget: text_input
  type:
    __datatype: str
    __label: streams/type
    __options:
    - ipv4
    - ipv6
    - ipv6pd
    __value: ipv4
    __widget: selectbox
- Gbps:
    __datatype: float
    __label: streams/Gbps
    __options:
      __max: 100.0
      __min: 0.0
      __step: 1.0
    __value: 6.0
    __widget: number_input
  direction:
    __datatype: str
    __label: streams/direction
    __options:
    - both
    - upstream
    - downstream
    __value: both
    __widget: selectbox
  length:
    __datatype: int
    __label: streams/length
    __options:
      __max: 9000
      __min: 76
      __step: 100
    __value: 3936
    __widget: number_input
  name:
    __datatype: str
    __label: streams/name
    __options: []
    __value: BE
    __widget: text_input
  stream-group-id:
    __datatype: str
    __label: streams/stream-group-id
    __options: []
    __value: 102
    __widget: text_input
  type:
    __datatype: str
    __label: streams/type
    __options:
    - ipv4
    - ipv6
    - ipv6pd
    __value: ipv4
    __widget: selectbox
- Mbps:
    __datatype: float
    __label: streams/Mbps
    __options:
      __max: 1024.0
      __min: 0.0
      __step: 10.0
    __value: 500.0
    __widget: number_input
  direction:
    __datatype: str
    __label: streams/direction
    __options:
    - both
    - upstream
    - downstream
    __value: both
    __widget: selectbox
  length:
    __datatype: int
    __label: streams/length
    __options:
      __max: 9000
      __min: 76
      __step: 100
    __value: 3936
    __widget: number_input
  name:
    __datatype: str
    __label: streams/name
    __options: []
    __value: EF
    __widget: text_input
  stream-group-id:
    __datatype: str
    __label: streams/stream-group-id
    __options: []
    __value: 103
    __widget: text_input
  type:
    __datatype: str
    __label: streams/type
    __options:
    - ipv4
    - ipv6
    - ipv6pd
    __value: ipv4
    __widget: selectbox
- Mbps:
    __datatype: float
    __label: streams/Mbps
    __options:
      __max: 1024.0
      __min: 0.0
      __step: 10.0
    __value: 500.0
    __widget: number_input
  direction:
    __datatype: str
    __label: streams/direction
    __options:
    - both
    - upstream
    - downstream
    __value: both
    __widget: selectbox
  length:
    __datatype: int
    __label: streams/length
    __options:
      __max: 9000
      __min: 76
      __step: 100
    __value: 3936
    __widget: number_input
  name:
    __datatype: str
    __label: streams/name
    __options: []
    __value: L1
    __widget: text_input
  stream-group-id:
    __datatype: str
    __label: streams/stream-group-id
    __options: []
    __value: 104
    __widget: text_input
  type:
    __datatype: str
    __label: streams/type
    __options:
    - ipv4
    - ipv6
    - ipv6pd
    __value: ipv4
    __widget: selectbox
- Mbps:
    __datatype: float
    __label: streams/Mbps
    __options:
      __max: 1024.0
      __min: 0.0
      __step: 10.0
    __value: 500.0
    __widget: number_input
  direction:
    __datatype: str
    __label: streams/direction
    __options:
    - both
    - upstream
    - downstream
    __value: both
    __widget: selectbox
  length:
    __datatype: int
    __label: streams/length
    __options:
      __max: 9000
      __min: 76
      __step: 100
    __value: 3936
    __widget: number_input
  name:
    __datatype: str
    __label: streams/name
    __options: []
    __value: L2
    __widget: text_input
  stream-group-id:
    __datatype: str
    __label: streams/stream-group-id
    __options: []
    __value: 105
    __widget: text_input
  type:
    __datatype: str
    __label: streams/type
    __options:
    - ipv4
    - ipv6
    - ipv6pd
    __value: ipv4
    __widget: selectbox
- Mbps:
    __datatype: float
    __label: streams/Mbps
    __options:
      __max: 1024.0
      __min: 0.0
      __step: 10.0
    __value: 500.0
    __widget: number_input
  direction:
    __datatype: str
    __label: streams/direction
    __options:
    - both
    - upstream
    - downstream
    __value: both
    __widget: selectbox
  length:
    __datatype: int
    __label: streams/length
    __options:
      __max: 9000
      __min: 76
      __step: 100
    __value: 3936
    __widget: number_input
  name:
    __datatype: str
    __label: streams/name
    __options: []
    __value: NC
    __widget: text_input
  stream-group-id:
    __datatype: str
    __label: streams/stream-group-id
    __options: []
    __value: 106
    __widget: text_input
  type:
    __datatype: str
    __label: streams/type
    __options:
    - ipv4
    - ipv6
    - ipv6pd
    __value: ipv4
    __widget: selectbox
