bgp:
  family:
    __datatype: str
    __label: bgp/family
    __options:
    - ipv4-unicast
    - ipv6-unicast
    - ipv4-multicast
    - ipv6-multicast
    - ipv4-labeled-unicast
    - ipv6-labeled-unicast
    - ipv4-vpn-unicast
    - ipv6-vpn-unicast
    - ipv4-vpn-multicast
    - ipv6-vpn-multicast
    - ipv4-flow
    - ipv6-flow
    - evpn
    __value:
    - ipv4-unicast
    __widget: multiselect
  local-address:
    __datatype: str
    __label: bgp/local-address
    __options: []
    __value: 174.10.10.1
    __widget: text_input
  local-as:
    __datatype: str
    __label: bgp/local-as
    __options: []
    __value: 7552
    __widget: text_input
  peer-address:
    __datatype: str
    __label: bgp/peer-address
    __options: []
    __value: 174.10.10.2
    __widget: text_input
  peer-as:
    __datatype: str
    __label: bgp/peer-as
    __options: []
    __value: 7552
    __widget: text_input
  raw-update-file:
    __datatype: str
    __label: bgp/raw-update-file
    __options: []
    __value: /var/bngblaster/47K_HOST.bgp
    __widget: text_input
interfaces:
  access:
  - address:
      __datatype: str
      __label: interfaces/access/address
      __options: []
      __value: 122.10.10.2
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/access/gateway
      __options: []
      __value: 122.10.10.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/access/interface
      __options: []
      __value: ens16.801
      __widget: text_input
    ipv6:
      __datatype: bool
      __label: interfaces/access/ipv6
      __options:
      - true
      - false
      __value: false
      __widget: selectbox
    stream-group-id:
      __datatype: int
      __label: interfaces/access/stream-group-id
      __options:
        __max: 65535
        __min: 0
        __step: 1000
      __value: 25
      __widget: number_input
    type:
      __datatype: str
      __label: interfaces/access/type
      __options:
      - pppoe
      - ipoe
      __value: ipoe
      __widget: selectbox
    vlan-mode:
      __datatype: str
      __label: interfaces/access/vlan-mode
      __options:
      - '1:1'
      - N:1
      __value: N:1
      __widget: selectbox
  network:
  - address:
      __datatype: str
      __label: interfaces/network/address
      __options: []
      __value: 174.10.10.1/30
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/network/gateway
      __options: []
      __value: 174.10.10.2
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/network/interface
      __options: []
      __value: ens17.801
      __widget: text_input
sessions:
  count:
    __datatype: str
    __label: sessions/count
    __options: []
    __value: 80
    __widget: text_input
