interfaces:
  access:
  - address:
      __datatype: str
      __label: interfaces/access/address
      __options: []
      __value: 10.121.0.3
      __widget: text_input
    address-iter:
      __datatype: str
      __label: interfaces/access/address-iter
      __options: []
      __value: 0.0.0.1
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/access/gateway
      __options: []
      __value: 10.121.0.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/access/interface
      __options: []
      __value: enp101s0np0
      __widget: text_input
    ipv6:
      __datatype: bool
      __label: interfaces/access/ipv6
      __options:
      - true
      - false
      __value: 'False'
      __widget: selectbox
    outer-vlan:
      __datatype: int
      __label: interfaces/access/outer-vlan
      __options:
        __max: 4094
        __min: 0
        __step: 1
      __value: 2221
      __widget: number_input
    stream-group-id:
      __datatype: int
      __label: interfaces/access/stream-group-id
      __options:
        __max: 65535
        __min: 0
        __step: 1000
      __value: 400
      __widget: number_input
    type:
      __datatype: str
      __label: interfaces/access/type
      __options:
      - pppoe
      - ipoe
      __value: ipoe
      __widget: selectbox
    vlan-mode:
      __datatype: str
      __label: interfaces/access/vlan-mode
      __options:
      - '1:1'
      - N:1
      __value: N:1
      __widget: selectbox
  io-slots:
    __datatype: str
    __label: interfaces/io-slots
    __options: []
    __value: '32768'
    __widget: text_input
  rx-interval:
    __datatype: float
    __label: interfaces/rx-interval
    __options:
      __max: 1000.0
      __min: 0.0001
      __step: 100.0
    __value: 0.01
    __widget: number_input
  rx-threads:
    __datatype: str
    __label: interfaces/rx-threads
    __options: []
    __value: '4'
    __widget: text_input
  tx-interval:
    __datatype: float
    __label: interfaces/tx-interval
    __options:
      __max: 1000.0
      __min: 0.0001
      __step: 100.0
    __value: 0.01
    __widget: number_input
  tx-threads:
    __datatype: str
    __label: interfaces/tx-threads
    __options: []
    __value: '4'
    __widget: text_input
sessions:
  count:
    __datatype: str
    __label: sessions/count
    __options: []
    __value: 64000
    __widget: text_input
  start-rate:
    __datatype: str
    __label: sessions/start-rate
    __options: []
    __value: 800
    __widget: text_input
