igmp:
  group:
    __datatype: str
    __label: igmp/group
    __options: []
    __value: 239.1.0.1
    __widget: text_input
  group-count:
    __datatype: int
    __label: igmp/group-count
    __options: []
    __value: 1
    __widget: text_input
  group-iter:
    __datatype: str
    __label: igmp/group-iter
    __options: []
    __value: 0.0.0.1
    __widget: text_input
  multicast-traffic-pps:
    __datatype: int
    __label: igmp/multicast-traffic-pps
    __options: []
    __value: 1000
    __widget: text_input
  send-multicast-traffic:
    __datatype: bool
    __label: igmp/send-multicast-traffic
    __options:
    - true
    - false
    __value: true
    __widget: selectbox
  source:
    __datatype: str
    __label: igmp/source
    __options: []
    __value: 10.63.1.1
    __widget: text_input
  start-delay:
    __datatype: int
    __label: igmp/start-delay
    __options: []
    __value: 2
    __widget: text_input
  version:
    __datatype: str
    __label: igmp/version
    __options:
    - '1'
    - '2'
    - '3'
    __value: '2'
    __widget: selectbox
interfaces:
  access:
  - address:
      __datatype: str
      __label: interfaces/access/address
      __options: []
      __value: 192.168.168.170
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/access/gateway
      __options: []
      __value: 192.168.168.169
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/access/interface
      __options: []
      __value: ens16.3888
      __widget: text_input
    ipv6:
      __datatype: bool
      __label: interfaces/access/ipv6
      __options:
      - true
      - false
      __value: false
      __widget: selectbox
    stream-group-id:
      __datatype: int
      __label: interfaces/access/stream-group-id
      __options:
        __max: 65535
        __min: 0
        __step: 1000
      __value: 1
      __widget: number_input
    type:
      __datatype: str
      __label: interfaces/access/type
      __options:
      - pppoe
      - ipoe
      __value: ipoe
      __widget: selectbox
    vlan-mode:
      __datatype: str
      __label: interfaces/access/vlan-mode
      __options:
      - '1:1'
      - N:1
      __value: N:1
      __widget: selectbox
  network:
  - address:
      __datatype: str
      __label: interfaces/network/address
      __options: []
      __value: 10.63.1.1/30
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/network/gateway
      __options: []
      __value: 10.63.1.2
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/network/interface
      __options: []
      __value: ens17.3888
      __widget: text_input
