bgp:
  family:
    __datatype: str
    __label: bgp/family
    __options:
    - ipv4-unicast
    - ipv6-unicast
    - ipv4-multicast
    - ipv6-multicast
    - ipv4-labeled-unicast
    - ipv6-labeled-unicast
    - ipv4-vpn-unicast
    - ipv6-vpn-unicast
    - ipv4-vpn-multicast
    - ipv6-vpn-multicast
    - ipv4-flow
    - ipv6-flow
    - evpn
    __value:
    - ipv4-unicast
    __widget: multiselect
  local-address:
    __datatype: str
    __label: bgp/local-address
    __options: []
    __value: 10.73.73.2
    __widget: text_input
  local-as:
    __datatype: str
    __label: bgp/local-as
    __options: []
    __value: '7552'
    __widget: text_input
  peer-address:
    __datatype: str
    __label: bgp/peer-address
    __options: []
    __value: 10.73.73.1
    __widget: text_input
  peer-as:
    __datatype: str
    __label: bgp/peer-as
    __options: []
    __value: '7552'
    __widget: text_input
  raw-update-file:
    __datatype: str
    __label: bgp/raw-update-file
    __options: []
    __value: /var/bngblaster/PE_4G_scaling/scale.bgp
    __widget: text_input
interfaces:
  network:
  - address:
      __datatype: str
      __label: interfaces/network/address
      __options: []
      __value: 10.73.73.2/24
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/network/gateway
      __options: []
      __value: 10.73.73.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/network/interface
      __options: []
      __value: ens17.73
      __widget: text_input
