dhcp:
  broadcast:
    __datatype: bool
    __label: dhcp/broadcast
    __options:
    - true
    - false
    __value: true
    __widget: selectbox
  enable:
    __datatype: bool
    __label: dhcp/enable
    __options:
    - true
    - false
    __value: true
    __widget: selectbox
interfaces:
  access:
  - gateway:
      __datatype: str
      __label: interfaces/access/gateway
      __options: []
      __value: 172.16.124.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/access/interface
      __options: []
      __value: ens17.301
      __widget: text_input
    ipv6:
      __datatype: bool
      __label: interfaces/access/ipv6
      __options:
      - true
      - false
      __value: false
      __widget: selectbox
    stream-group-id:
      __datatype: int
      __label: interfaces/access/stream-group-id
      __options:
        __max: 65535
        __min: 0
        __step: 1000
      __value: 3854
      __widget: number_input
    type:
      __datatype: str
      __label: interfaces/access/type
      __options:
      - pppoe
      - ipoe
      __value: ipoe
      __widget: selectbox
    vlan-mode:
      __datatype: str
      __label: interfaces/access/vlan-mode
      __options:
      - '1:1'
      - N:1
      __value: N:1
      __widget: selectbox
  io-slots:
    __datatype: str
    __label: interfaces/io-slots
    __options: []
    __value: 65535
    __widget: text_input
  rx-threads:
    __datatype: str
    __label: interfaces/rx-threads
    __options: []
    __value: 5
    __widget: text_input
  tx-threads:
    __datatype: str
    __label: interfaces/tx-threads
    __options: []
    __value: 5
    __widget: text_input
sessions:
  count:
    __datatype: str
    __label: sessions/count
    __options: []
    __value: 100
    __widget: text_input
