[auth]
redirect_uri = "https://bngblaster.linhchai.id.vn/bngblaster/oauth2callback"
cookie_secret = "f7a9c2e1b4d6e8f0a3c5b7d9e2f4a6c8"
client_id = "879229682557-ucaesbgkes6f3e508vek8fnkc1066vef.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"